version: "3.9"
services:
  web:
    build: ./frontend
    ports:
      - 3000:80
  backend:
    build: ./backend
    ports:
      - 4000:4000
    environment:
      - DATABASE_URL=mysql://root@db:3306/my_app?schema=public
  db:
    image: mysql:8.0.28
    ports:
      - 3306:3306
    command: >
      --skip-character-set-client-handshake
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./db/mysql:/var/lib/mysql
      - ./db/initdb.d:/docker-entrypoint-initdb.d
    environment:
      - LANG=C.UTF-8
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=my_app
